import { createServerFn } from "@tanstack/react-start";

import { type User } from "../types/users";

export const users: User[] = [
  {
    id: "USER-001",
    name: "John Doe",
    email: "john.doe@example.com",
    role: "admin",
    status: "active",
    avatar: "",
    joinDate: "2024-01-15",
  },
  {
    id: "USER-002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-01-20",
  },
  {
    id: "USER-003",
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    role: "moderator",
    status: "inactive",
    avatar: "",
    joinDate: "2024-01-10",
  },
  {
    id: "USER-004",
    name: "Alice Williams",
    email: "alice.williams@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-02-05",
  },
  {
    id: "USER-005",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    role: "user",
    status: "inactive",
    avatar: "",
    joinDate: "2024-01-25",
  },
  {
    id: "USER-006",
    name: "Diana Prince",
    email: "diana.prince@example.com",
    role: "moderator",
    status: "active",
    avatar: "",
    joinDate: "2024-02-10",
  },
  {
    id: "USER-007",
    name: "Edward Norton",
    email: "edward.norton@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-02-15",
  },
  {
    id: "USER-008",
    name: "Fiona Gallagher",
    email: "fiona.gallagher@example.com",
    role: "admin",
    status: "active",
    avatar: "",
    joinDate: "2024-02-18",
  },
  {
    id: "USER-009",
    name: "George Martin",
    email: "george.martin@example.com",
    role: "user",
    status: "inactive",
    avatar: "",
    joinDate: "2024-01-30",
  },
  {
    id: "USER-010",
    name: "Hannah Baker",
    email: "hannah.baker@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-03-01",
  },
  {
    id: "USER-011",
    name: "Ian Curtis",
    email: "ian.curtis@example.com",
    role: "moderator",
    status: "inactive",
    avatar: "",
    joinDate: "2024-03-03",
  },
  {
    id: "USER-012",
    name: "Julia Roberts",
    email: "julia.roberts@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-03-05",
  },
  {
    id: "USER-013",
    name: "Kevin Malone",
    email: "kevin.malone@example.com",
    role: "user",
    status: "inactive",
    avatar: "",
    joinDate: "2024-02-28",
  },
  {
    id: "USER-014",
    name: "Laura Palmer",
    email: "laura.palmer@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-03-10",
  },
  {
    id: "USER-015",
    name: "Mike Ross",
    email: "mike.ross@example.com",
    role: "admin",
    status: "active",
    avatar: "",
    joinDate: "2024-03-12",
  },
  {
    id: "USER-016",
    name: "Nina Simone",
    email: "nina.simone@example.com",
    role: "moderator",
    status: "inactive",
    avatar: "",
    joinDate: "2024-03-14",
  },
  {
    id: "USER-017",
    name: "Oscar Wilde",
    email: "oscar.wilde@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-03-16",
  },
  {
    id: "USER-018",
    name: "Paula Abdul",
    email: "paula.abdul@example.com",
    role: "user",
    status: "active",
    avatar: "",
    joinDate: "2024-03-18",
  },
  {
    id: "USER-019",
    name: "Quentin Blake",
    email: "quentin.blake@example.com",
    role: "user",
    status: "inactive",
    avatar: "",
    joinDate: "2024-03-20",
  },
  {
    id: "USER-020",
    name: "Rachel Green",
    email: "rachel.green@example.com",
    role: "admin",
    status: "active",
    avatar: "",
    joinDate: "2024-03-22",
  },
];

export const getUsers = createServerFn({ method: "GET" }).handler(async () => {
  const filteredUsers = [...users];
  return filteredUsers;
});
